### ISSUE TITLE
Fart på Hjulet

### ISSUE THREAD

**Issue by Krumme2004** [CecilieMarieJ/CMJ_HTX_21-22#1]
Cecilie har bedt mig om at kigge på at få hendes hjul til at køre hurtigere.
[Koden til hjulet](https://github.com/CecilieMarieJ/CMJ_HTX_21-22/blob/main/Opgaver/Uge_36_opgave_1/Uge_36_opgave_1.pde)
I denne kode kan værdien for integeren "hjul" gøres højere og samtidigt skal rotate forøges, disse findes på linje:
10 
16

**Comment by CecilieMarieJ** [comment]
Thank you
